version: '3.5'
services:
  database:
    container_name: easymlpostgres
    image: postgres:latest
    env_file: database.conf
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - db_volume:/var/lib/postgresql
  web:
    build: .
    env_file: database.conf
    ports:
      - "5000:5000"




volumes:
  db_volume: