"""empty message

Revision ID: ad1970a23faf
Revises: 1fb898e0546b
Create Date: 2019-10-06 18:55:05.303895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1970a23faf'
down_revision = '1fb898e0546b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('files', 'id', type_=sa.String(length=40))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
