"""empty message

Revision ID: d09fcfe92960
Revises: ad1970a23faf
Create Date: 2019-10-07 17:46:47.971680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09fcfe92960'
down_revision = 'ad1970a23faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('header', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('files', 'header')
    # ### end Alembic commands ###
